# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stringer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stringer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0estringer.proto\",\n\rResultRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"\x1e\n\x0eResultResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2=\n\x08Stringer\x12\x31\n\x0c\x61\x64\x64string_id\x12\x0e.ResultRequest\x1a\x0f.ResultResponse\"\x00\x62\x06proto3')
)




_RESULTREQUEST = _descriptor.Descriptor(
  name='ResultRequest',
  full_name='ResultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='ResultRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ResultRequest.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=62,
)


_RESULTRESPONSE = _descriptor.Descriptor(
  name='ResultResponse',
  full_name='ResultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='ResultResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['ResultRequest'] = _RESULTREQUEST
DESCRIPTOR.message_types_by_name['ResultResponse'] = _RESULTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResultRequest = _reflection.GeneratedProtocolMessageType('ResultRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESULTREQUEST,
  __module__ = 'stringer_pb2'
  # @@protoc_insertion_point(class_scope:ResultRequest)
  ))
_sym_db.RegisterMessage(ResultRequest)

ResultResponse = _reflection.GeneratedProtocolMessageType('ResultResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESULTRESPONSE,
  __module__ = 'stringer_pb2'
  # @@protoc_insertion_point(class_scope:ResultResponse)
  ))
_sym_db.RegisterMessage(ResultResponse)



_STRINGER = _descriptor.ServiceDescriptor(
  name='Stringer',
  full_name='Stringer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=96,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='addstring_id',
    full_name='Stringer.addstring_id',
    index=0,
    containing_service=None,
    input_type=_RESULTREQUEST,
    output_type=_RESULTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STRINGER)

DESCRIPTOR.services_by_name['Stringer'] = _STRINGER

# @@protoc_insertion_point(module_scope)
